### ISSUE TITLE
Error probing device: Error sending ATA command IDENTIFY DEVICE to '/dev/sda': Unexpected sense data returned since kernel 6.10.3 update

### ISSUE THREAD

**Issue by tomporter518** [storaged-project/udisks#1305] opened 2024-08-09 18:48 UTC
Not sure if this is a duplicate. The recent kernel 6.10.3 update that Fedora 40 took on might have surfaced this. I found this kernel discussion thread and wonder if it could be related: [hdparm errors since 28ab9769117c](https://lore.kernel.org/lkml/45cdf1c2-9056-4ac2-8e4d-4f07996a9267@kernel.org/T/#m1d0a754dbfd5a2462fb75282f3f7942b8f867371) referenced from [Lm_Sensor depending Proggies not showing temperature of SATA-drives](https://forum.manjaro.org/t/lm-sensor-depending-proggies-not-showing-temperature-of-sata-drives/166492/8). I noticed that Freon was no longer showing my HD temps and I cannot access the ATA DBUS interface of udisks2.
```
dbus-send --system --dest=org.freedesktop.UDisks2 --print-reply /org/freedesktop/UDisks2/drives/WDC__WDBNCE0010PNC_21070X808522 org.freedesktop.DBus.Properties.Get string:org.freedesktop.UDisks2.Drive.Ata string:SmartTemperature
Error org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.UDisks2.Drive.Ata”
```

**Comment by bsdice** [comment] 2024-08-09 19:47
Duplicate of https://github.com/storaged-project/udisks/issues/732

**Comment by tbzatek** [comment] 2024-08-12 12:15
The messages may look optically similar but they're about different kind of devices (USB vs. SATA and disk drive vs. optical drive).

**Comment by axet** [comment] 2024-08-17 08:59
Could be:

* https://git.kernel.org/pub/scm/linux/kernel/git/libata/linux.git/commit/?id=fa0db8e5

**Closed** 2024-09-10 18:09 UTC
