### ISSUE TITLE
dosfstools-4.2 breaks vfat formatting of entire device (debian-testing)

### ISSUE THREAD

**Issue by allisonkarlitskaya** [storaged-project/udisks#851] opened 2021-03-01 15:50 UTC
hello,

Here's a bug from debian-testing, which claims to be shipping a vanilla udisks 2.9.1.  They've asked me to forward this upstream.

A new version of dosfstools (4.2) just landed on testing, and we're suddenly seeing a new failure in cockpit's integration testing: specifically, attempting to create a fat filesystem on /dev/sda (the direct device, not a partition) fails.  This works correctly with dosfstools 4.1.

See https://github.com/cockpit-project/bots/pull/1701 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=983751.

This problem is not limited to cockpit, however. You can see the problem rather directly with this reproducer:

```
root@debian:~# dpkg -i dosfstools_4.1-2_amd64.deb
dpkg: warning: downgrading dosfstools from 4.2-1 to 4.1-2
(Reading database ... 70287 files and directories currently installed.)
Preparing to unpack dosfstools_4.1-2_amd64.deb ...
Unpacking dosfstools (4.1-2) over (4.2-1) ...
Setting up dosfstools (4.1-2) ...
Processing triggers for man-db (2.9.4-1) ...
root@debian:~# gdbus call --system --dest org.freedesktop.UDisks2 --object-path /org/freedesktop/UDisks2/block_devices/sda --method org.freedesktop.UDisks2.Block.Format vfat '{}'
()
```

but then:

```
root@debian:~# dpkg -i dosfstools_4.2-1_amd64.deb
(Reading database ... 70285 files and directories currently installed.)
Preparing to unpack dosfstools_4.2-1_amd64.deb ...
Unpacking dosfstools (4.2-1) over (4.1-2) ...
Setting up dosfstools (4.2-1) ...
Processing triggers for man-db (2.9.4-1) ...
root@debian:~# gdbus call --system --dest org.freedesktop.UDisks2 --object-path /org/freedesktop/UDisks2/block_devices/sda --method org.freedesktop.UDisks2.Block.Format vfat '{}'
Error: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error synchronizing after formatting with type `vfat': Timed out waiting for object
```

note that attempting to format a partition works fine, even with the new version:
```
root@debian:~# fdisk /dev/sda
[ ... create primary partition /dev/sda1 ... ]
Command (m for help): w
The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

root@debian:~# gdbus call --system --dest org.freedesktop.UDisks2 --object-path /org/freedesktop/UDisks2/block_devices/sda1 --method org.freedesktop.UDisks2.Block.Format vfat '{}'
()
```

**Comment by tbzatek** [comment] 2021-03-01 15:55
Hi Allison,

this is https://github.com/storaged-project/libblockdev/pull/618. Not sure what are the plans to roll a new stable `libblockdev` release (@vojtechtrefny ?), probably worth patching the current downstream packages in the meantime (@seb128 FYI).

**Comment by allisonkarlitskaya** [comment] 2021-03-01 15:59
Cool!  Thanks :)

**Comment by tbzatek** [comment] 2021-03-01 16:32
FYI @pali - I think you were involved in the recent `dosfstools` changes. While I understand the rationale behind the behavioral changes (aka. breaking the commandline tools ABI for the sake of doing the right thing), just wanted to point out that UDisks d-bus testsuite can be actually used as a verification tool for checking regressions. Both UDisks and libblockdev are calling many commandline tools that don't provide a library, `udftools` being another example. Cockpit provides a pretty extensive testsuite as well, although it might be a little complex to set it up.

**Comment by pali** [comment] 2021-03-01 16:39
And what is the issue? I do not see any error message in this issue report related to dosfstools or udftools.

**Comment by vojtechtrefny** [comment] 2021-03-02 11:42
> this is [storaged-project/libblockdev#618](https://github.com/storaged-project/libblockdev/pull/618). Not sure what are the plans to roll a new stable `libblockdev` release (@vojtechtrefny ?), probably worth patching the current downstream packages in the meantime (@seb128 FYI).

New release of libblockdev won't fix it, we are not running `mkfs.vfat` with `--mbr=n` by default, the change was only in tests. The problem here is that UDisks is formatting `sda` to VFAT and expects that after the action `sda` will be formatted to VFAT which isn't true with dosfstools 4.2 (new partition formatted to VFAT is created).

**Comment by pali** [comment] 2021-03-02 11:50
> we are not running `mkfs.vfat` with `--mbr=n` by default

You should not set it by default. Otherwise such `sda` disk would not be readable by microsoft systems.

> is formatting `sda` to VFAT and expects that after the action `sda` will be formatted to VFAT which isn't true with dosfstools 4.2

`sda` should be to VFAT also in this case. If it is not valid VFAT anymore then it is a bug. But in all my tests I get only valid VFAT, so I was not able to reproduce this issue. Could you describe in more details what is not valid on that VFAT disk and what e.g. kernel prints when trying to mount it as VFAT? I will try to look at it and fix it.

**Comment by vojtechtrefny** [comment] 2021-03-02 12:00
> `sda` should be to VFAT also in this case. If it is not valid VFAT anymore then it is a bug. But in all my tests I get only valid VFAT, so I was not able to reproduce this issue. Could you describe in more details what is not valid on that VFAT disk and what e.g. kernel prints when trying to mount it as VFAT? I will try to look at it and fix it.

This is not about mounting the device, we get the information from UDev database which uses libblkid to detect filesystems and form our point of view there is a disk with MSDOS partition table with single VFAT partition:

```
# blkid -p /dev/sda
/dev/sda: PTUUID="a8ac4eda" PTTYPE="dos"
```

after formatting `sda` we wait until the change is reflected in UDev database and in this case this never happens.

**Comment by pali** [comment] 2021-03-02 12:19
Ah, that is different issue :-(

Can you reproduce this issue also with `mkudffs` and `mformat`? Or it is specific to `mkfs.vfat`?

**Comment by tbzatek** [comment] 2021-03-12 16:32
Right, the UDF case of creating compatible partition table is similar and also not fully working in UDisks as of yet (occassional test failures appearing). On a TODO list.

UDisks in this recent `mkfs.vfat` change is a victim in the middle layer. On one side `mkfs.vfat` is trying to do the right thing in terms of compatibility, on the other side UDisks consumers are expected to see a filesystem created with no extra frills yet they get a partition table as a bonus. The decision for formatting over a non-partitioned block device, the responsibility for this decision and the higher level logic is on the consumer side, UDisks is just a tool that is expected to work as specified with consistent behaviour across releases for a stable API. For that reason we'll be forced to always supply the `--mbr=n` argument to get the old behaviour that the clients expect back.

It's crucial to stress the importance of a consistent and expected behaviour that boils down to the external tools that are called.

**Comment by tbzatek** [comment] 2021-03-17 17:57
The good-or-bad way discussion has been moved to a private e-mail thread with the ideas being fed into a separate ticket: #859

**Closed** 2021-03-24 14:46 UTC
