### ISSUE TITLE
RFE: please provide update for latest iscsi-initiator-utils

### ISSUE THREAD

**Issue by kloczek** [storaged-project/udisks#1135] opened 2023-06-30 16:04 UTC
Latest version https://github.com/open-iscsi/open-iscsi is 2.1.9.
Looks like it is not possible to build udisk 3.0 against that version and configure fails with
```console
checking for libiscsi.h... no
checking for libiscsi_init in -liscsi... no
configure: error: iSCSI support requested but libraries not found
```
(probably it would be good to switch h to pkgconfig as well)

**Comment by tbzatek** [comment] 2023-06-30 16:12
This is a pure duplicate of your issue #1122. Please read my comments there, note that the `libiscsi` is a downstream Fedora/CentOS Stream/RHEL patch only and what we plan to do: https://github.com/storaged-project/udisks/issues/1122#issuecomment-1598425025

**Closed by tbzatek** 2023-06-30 16:12 UTC
