### ISSUE TITLE
version 2.10.0 and version 2.10.1 are causing lots of issues

### ISSUE THREAD

**Issue by JaKooLit** [storaged-project/udisks#1195] opened 2023-09-30 00:20 UTC
Issues:
These 2 versions makes all drives / partitions, except for system partition, to appear as removable on any file managers. File manager tested: Thunar, dolphin, pcmanfm.

when executing a file manager, here is the journalctl -xeu udisks2.service message

 

> Sep 30 08:41:26 Gen2-HyprLanD systemd[1]: Starting udisks2.service...
> 
> ░░ Subject: A start job for unit udisks2.service has begun execution
> ░░ Defined-By: systemd
> ░░ Support: https://gentoo.org/support/
> ░░ 
> ░░ A start job for unit udisks2.service has begun execution.
> ░░ 
> ░░ The job identifier is 2126.
> Sep 30 08:41:26 Gen2-HyprLanD udisksd[4318]: udisks daemon version 2.10.1 starting
> Sep 30 08:41:31 Gen2-HyprLanD systemd[1]: udisks2.service: start operation timed out. Terminating.
> Sep 30 08:41:36 Gen2-HyprLanD systemd[1]: udisks2.service: State 'stop-sigterm' timed out. Killing.
> Sep 30 08:41:36 Gen2-HyprLanD systemd[1]: udisks2.service: Killing process 4318 (udisksd) with signal SIGKILL.
> Sep 30 08:41:36 Gen2-HyprLanD systemd[1]: udisks2.service: Killing process 4319 (gmain) with signal SIGKILL.
> Sep 30 08:41:36 Gen2-HyprLanD systemd[1]: udisks2.service: Killing process 4320 (pool-spawner) with signal SIGKILL.
> Sep 30 08:41:36 Gen2-HyprLanD systemd[1]: udisks2.service: Main process exited, code=killed, status=9/KILL
> ░░ Subject: Unit process exited
> ░░ Defined-By: systemd
> ░░ Support: https://gentoo.org/support/
> ░░ 
> ░░ An ExecStart= process belonging to unit udisks2.service has exited.
> ░░ 
> ░░ The process' exit code is 'killed' and its exit status is 9.
> Sep 30 08:41:36 Gen2-HyprLanD systemd[1]: udisks2.service: Failed with result 'timeout'.
> ░░ Subject: Unit failed
> ░░ Defined-By: systemd
> ░░ Support: https://gentoo.org/support/
> ░░ 
> ░░ The unit udisks2.service has entered the 'failed' state with result 'timeout'.
> Sep 30 08:41:36 Gen2-HyprLanD systemd[1]: Failed to start udisks2.service.
> ░░ Subject: A start job for unit udisks2.service has failed
> ░░ Defined-By: systemd
> ░░ Support: https://gentoo.org/support/
> ░░ 
> ░░ A start job for unit udisks2.service has finished with a failure.
> ░░ 
> ░░ The job identifier is 2126 and the job result is failed.

no issues on older versions, in particular: ver 2.9.4 r3

**Comment by tbzatek** [comment] 2023-10-02 11:12
This looks essentially like #1192. Would you be able to debug that and provide some backtrace please?

**Comment by tbzatek** [comment] 2023-10-02 11:18
Could you also attach `emerge --info udisks libblockdev libnvme` and `udevadm info -e` please?

**Comment by JaKooLit** [comment] 2023-10-02 12:00
> udevadm info -e

I have to figure out how to debug and backtrace as I have never done that tbh :)

anyway, here's the requested emerge --info and udevadm info
[emergeinfo.txt](https://github.com/storaged-project/udisks/files/12782390/emergeinfo.txt)
[udevadm.txt](https://github.com/storaged-project/udisks/files/12782391/udevadm.txt)

**Comment by tbzatek** [comment] 2023-10-02 14:28
Thanks, your storage setup is pretty complex, though the udevadm dump looks sane. The `emerge --info` output is with old versions, I'd be interested in USE flags for the new releases.

If you have a room for experiments, let's try this:
- `FEATURES="splitdebug nostrip" CFLAGS="-O0 -ggdb" USE="debug" emerge libnvme libblockdev udisks`
- `emerge --info udisks libblockdev libnvme`
- `G_DEBUG=resident-modules valgrind --leak-check=full --leak-resolution=high --num-callers=20 --log-file=vgdump.log /usr/libexec/udisks2/udisksd --replace --debug --disable-modules`

Let's see if we can get any meaningul output from `vgdump.log`. As we have no idea what the problem is so far, any useful symbol name would be a good start.

**Comment by JaKooLit** [comment] 2023-10-02 16:36
Thanks alot of the detailed instructions as wouldnt know where to start.

Anyway, I have to comeback with the vgdump.log as its been more than an hour since I started and hasnt done. I recon gonna takes more few hours to complete

Anyway, here's the emerge-info with newer packages 
[emerge-info.txt](https://github.com/storaged-project/udisks/files/12784561/emerge-info.txt)

**Comment by tbzatek** [comment] 2023-10-02 16:42
> Anyway, I have to comeback with the vgdump.log as its been more than an hour since I started and hasnt done. I recon gonna takes more few hours to complete

Oh, right, that could take even days, valgrind is very slow. I think if you terminate it by Ctrl+C, there might be something useful logged already. If there's a memleak somewhere, it would be just a repeating pattern.

I'm also thinking that might be wise to limit the testing environment (e.g. via `ulimit`) so that memory runs out sooner.

**Comment by JaKooLit** [comment] 2023-10-02 16:47
[vgdump.log](https://github.com/storaged-project/udisks/files/12784671/vgdump.log)
ok I terminate and here's the log

**Comment by JaKooLit** [comment] 2023-10-02 17:13
alright thanks. Ill do that later on and will revert. need to get some sleep

**Comment by JaKooLit** [comment] 2023-10-03 01:54
So probably Im not doing right but I found also about systemd-run memory limit....

so I created udisks.sh with ``G_DEBUG=resident-modules valgrind --leak-check=full --leak-resolution=high --num-callers=20 --log-file=vgdump.log /usr/libexec/udisks2/udisksd --replace --debug --disable-modules``

and ran

``systemd-run --scope -p MemoryMax=250M -p MemoryHigh=200M ./udisks.sh`` 

been running for some time (1hr) and not failing. and I think the systemd-run just slow down



Anyway, just to give you also something. Maybe will help you. Maybe not.

On my desktop.
I have the following on a different disks / partition

issue with udisks v2.10.1
- Arch Plasma
- Arch Gnome
- Gentoo - Hyprland

No issue with udisks v2.10.1
- Arch Hyprland
- Fedora Gnome/Hyprland


Kindly take note that they are in different disks / partitions


I'd also would like to tell you that I dont have issue on my laptop. with Arch-Plasma, Arch-Hyprland, Fedora Gnome/Hyprland, Gentoo-Hyprland


Thats why before reporting here, I am scratching my head comparing use flags between my desktop and laptop....


If the information above tells you something, then its good, otherwise, let me know if there are some test you want me to do to help you figure out.....

Thanks

**Comment by tbzatek** [comment] 2023-10-05 15:23
One hint to check: try setting a breakpoint for `bd_nvme_find_ctrls_for_ns()` and see if the call returns or gets stuck.

**Comment by JaKooLit** [comment] 2023-10-05 15:31
gonna do debugging next week as I am not at home atm.

**Comment by JaKooLit** [comment] 2023-10-09 15:12
Ok... so a long day... tried all sorts of things, even downgrading PCI-E versions... and comes to a last test. Removing my nvme's. Cloned my Gentoo into one of my SSD's. removed my nvme's and dang NO ISSUES!

So should I close this issue and open a new one or I can just tell you here my nvmes?

My nvme's are by Seagate FireCuda 520 and 530 Series

or needed more info?

**Comment by tbzatek** [comment] 2023-10-09 15:54
As a matter of fact, my primary development system is running Gentoo amd64 (stable) with FireCuda 520. So my setup is very close to yours and I still wonder what's so different. Though I'm still on 6.2.2 kernel, need to find some time to try a new one.

Bot Firecuda 520 and 530 are Phison controllers, E16 vs. E18, I don't expect any significant difference.

**Comment by JaKooLit** [comment] 2023-10-10 00:18
So long story short, I have upgraded firmwares on both my nvme's and now all weird issues connected to latest udisks are gone

```
smartctl -i /dev/nvme0n1
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.5.6-gentoo-Ja-HyprLanD] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Seagate FireCuda 530 ZP2000GM30013
Serial Number:                      xxxxx
Firmware Version:                   SU6SM005
PCI Vendor/Subsystem ID:            0x1bb1
IEEE OUI Identifier:                0x6479a7
Total NVM Capacity:                 2,000,398,934,016 [2.00 TB]
Unallocated NVM Capacity:           0
Controller ID:                      1
NVMe Version:                       1.4
Number of Namespaces:               1
Namespace 1 Size/Capacity:          2,000,398,934,016 [2.00 TB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            6479a7 6d3f00ff25
Local Time is:                      Tue Oct 10 09:14:40 2023 KST
```

```
smartctl -i /dev/nvme1n1
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.5.6-gentoo-Ja-HyprLanD] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Seagate FireCuda 520 SSD ZP1000GM30002
Serial Number:                      xxxxx
Firmware Version:                   STNSC016
PCI Vendor/Subsystem ID:            0x1bb1
IEEE OUI Identifier:                0x0024cf
Total NVM Capacity:                 1,000,204,886,016 [1.00 TB]
Unallocated NVM Capacity:           0
Controller ID:                      1
NVMe Version:                       1.3
Number of Namespaces:               1
Namespace 1 Size/Capacity:          1,000,204,886,016 [1.00 TB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            0024cf 0150003b6b
Local Time is:                      Tue Oct 10 09:14:44 2023 KST
```

Still quite a puzzle why 2 of my distros in same machine was not affected by it though....

**Comment by tbzatek** [comment] 2023-10-10 12:33
Fascinating. I have had issues with the TRIM command on my Firecuda 520 running STNSC014 firmware. Update to STNSC016 fixed it. Some more Phison E12 and E16 drives used to have similar problem. Looks like it was not the only issue out there.

FYI, the issue should be fixed by https://github.com/storaged-project/libblockdev/pull/969 as confirmed in #1192.

Thanks for your help anyway!

**Closed by tbzatek** 2023-10-10 12:33 UTC
