### ISSUE TITLE
Wrong disk temperature for ssd

### ISSUE THREAD

**Issue by keikari** [storaged-project/udisks#568] opened 2018-08-22 15:50 UTC
Temperature shown for my SSD (KINGSTON_SA400S37240G) is 97°C-98°C. When correct temp is usually 28°C-33°C. It shows correct temp for my HDD. 
I hope this is correct place and way to inform this. (And correct program)
I have no idea what kind of info I should add.
![selection_010](https://user-images.githubusercontent.com/34790748/44474595-b54ffe80-a63b-11e8-8f0d-0c055e93f61f.png)

**Comment by tbzatek** [comment] 2018-08-22 16:03
Could you please provide output of `udisksctl dump` and `smartctl -a /dev/sda`? Most likely this is either malformed SMART structure reported by the drive or some _libatasmart_ issue. Nothing unusual sadly.

**Comment by keikari** [comment] 2018-08-22 16:09
Here
[smartctl_sda.txt](https://github.com/storaged-project/udisks/files/2311120/smartctl_sda.txt)
[udisk_dump.txt](https://github.com/storaged-project/udisks/files/2311121/udisk_dump.txt)

**Comment by tbzatek** [comment] 2018-08-22 16:28
Thanks, so the drive actually provides two temperature attributes - SMART ID 194 (31 deg. C) and ID 231 (97). Looks like we either need to tweak the attribute priority or provide a quirk for this drive model.

**Comment by keikari** [comment] 2018-08-22 18:28
I forgot to mention that my udisks version is 2.7.6 (current fedora version)

**Comment by elpop** [comment] 2019-06-07 04:48
Same here:

[pop@pop ~]$ hddtemp /dev/sda
/dev/sda: KINGSTON SA400S37480G: 56°C
[pop@pop ~]$ sudo smartctl -a /dev/sda | grep 194
194 Temperature_Celsius     0x0022   044   060   000    Old_age   Always       -       56 (Min/Max 23/60)

but udisk2 show 100c

Exists a param (udisks2.conf) to asigne register 194 to the temp attribute?

**Comment by sharkguto** [comment] 2020-07-05 16:37
same issue here with ubuntu 20.04

**Comment by seb128** [comment] 2020-07-07 14:52
The issue seems to be a libatasmart one, reported in https://bugs.freedesktop.org/show_bug.cgi?id=97446

There is an Ubuntu bug with some extra context and explanations where
Trent Nelson (trent-a-b-nelson) attached a patch to add a quirk
https://bugs.launchpad.net/ubuntu/+source/libatasmart/+bug/1581594/comments/16

The freedesktop bugzilla is locked down but libatasmart doesn't seem to have migrated to gitlab, unsure what's the right way to get a fix landed there?

**Comment by t-nelson** [comment] 2020-08-01 19:11
:wave:

**Comment by boredazfcuk** [comment] 2020-08-10 23:02
I'm seeing this too:
![Patriot Burst Incorrect Temp](https://user-images.githubusercontent.com/14807258/89838987-93235400-db64-11ea-8499-f84fcd40baf4.PNG)

Smart is showing correct temperature:
```
>smartctl --all /dev/sda | grep "^190\|^194"
194 Temperature_Celsius     0x0023   067   067   000    Pre-fail  Always       -       33 (Min/Max 33/33)
```

 ...but udisksctl does not:
```
>udisksctl dump | grep "Model:\|SmartTemp"
    Model:                      Patriot Burst
    SmartTemperature:                           372.15000000000003
    Model:                      ST6000VN0033-2EE110
    SmartTemperature:                           301.15000000000003
    Model:                      TOSHIBA MQ01ABD050
    SmartTemperature:                           307.15000000000003
    Model:                      WDC WD40EFRX-68WT0N0
    SmartTemperature:                           298.15000000000003
```

**Comment by Micronetic** [comment] 2020-08-25 15:14
Got the same problem
![Bildschirmfoto von 2020-08-25 17-01-57](https://user-images.githubusercontent.com/57453593/91192625-735c6600-e6f6-11ea-9637-41320e81084c.png)

**Comment by victor-bayas** [comment] 2020-11-29 22:39
Same problem on Arch Linux
![imagen](https://user-images.githubusercontent.com/49411169/100555452-8f2d5600-3269-11eb-9735-13aed34a558a.png)

hddtemp reports correct readings
![imagen](https://user-images.githubusercontent.com/49411169/100555480-ba17aa00-3269-11eb-8593-ccbb6fbbefee.png)

120GB Kingston A400 firmware is updated to version SBFKB1H5

**Comment by devbapidey** [comment] 2021-01-11 17:19
Same problem here. Confirmed!

**Comment by mohamedation** [comment] 2021-02-04 06:01
this is still an issue.

**Comment by michael-andreev** [comment] 2021-02-09 14:37
Same problem with `KINGSTON SA400S37120G` on Ubuntu 20.04. Another drive (`WDC WD60PURZ-85ZUFY1`) shows correct temperature.

**Comment by chutetearer** [comment] 2021-02-11 07:57
Same problem here too with a KINGSTON SA400S37480G on Mint 20.1 (Kernel Linux 5.4.0-65-generic x86_64)

**Comment by tbzatek** [comment] 2021-02-16 12:48
See #433 for the status on this issue.

**Comment by Dirli** [comment] 2021-03-09 22:28
It seems to me that the temperature does not give out correctly, or rather it does not give out the temperature. I use Vala and UDisks lib. When I output the attributes, I get the following output:
![udisks_gigabyte](https://user-images.githubusercontent.com/15650716/110545627-6eb14980-813e-11eb-91a7-ef4b96b54753.png)
when I use smartmontools I get the following output
![smart_gigabyte](https://user-images.githubusercontent.com/15650716/110545799-afa95e00-813e-11eb-8287-9748a2dea320.png)
the value itself is returned correctly if it is converted from Kelvin to Celsius. 
This is confirmed on two disks (Gigabyte, Smartbuy)

DriveAta.smart_temperature also gives the value of  ssd life

**Comment by devbapidey** [comment] 2021-03-15 08:04
> Thanks, so the drive actually provides two temperature attributes - SMART ID 194 (31 deg. C) and ID 231 (97). Looks like we either need to tweak the attribute priority or provide a quirk for this drive model.

when you are going to do it?

**Comment by mohamedation** [comment] 2022-03-30 13:07
is there any progress on that? or a workaround?

**Comment by tbzatek** [comment] 2022-03-30 13:39
> is there any progress on that? or a workaround?

Not for the moment, still busy with the NVMe stuff (and lower layers).

**Comment by othqsa95** [comment] 2023-02-07 21:48
Same problem here.

![img_1_1675806476854](https://user-images.githubusercontent.com/60115626/217374289-98e6045d-ba5a-4bb8-b4da-ee5456ef7c41.jpg)

**Comment by scottbomb** [comment] 2023-07-08 19:44
Still seeing this in 22.04.
`scottbomb@main:~/bin$ sudo udisksctl dump | grep "Model:\|SmartTemp"
    Model:                      ATAPI   iHAS124   F
    SmartTemperature:                           0.0
    Model:                      Hitachi HUS724040ALE641
    SmartTemperature:                           309.15000000000003
    Model:                      ST4000DM000-1F2168
    SmartTemperature:                           305.15000000000003
    Model:                      TOSHIBA DT01ACA200
    SmartTemperature:                           307.15000000000003
    Model:                      TOSHIBA THNSNC128GCSJ
    SmartTemperature:                           301.15000000000003
    Model:                      WDC WD40EZRX-00SPEB0
    SmartTemperature:                           306.15000000000003
`

**Comment by Neural-network-N** [comment] 2023-09-25 18:17
Good evening!

I guess that I have the same issue. Psensor shows wrong SSD temperature. Is is the right thread? 
![image](https://github.com/storaged-project/udisks/assets/85010168/e93a4403-33ca-402d-821a-845565092b6b)

**Comment by tbzatek** [comment] 2024-01-25 13:57
Reporters (@keikari, @elpop, @sharkguto, @boredazfcuk, @ghost, @bayasdev, @devbapidey, @mohamedation, @michael-andreev, @chutetearer, @Dirli, @othqsa95, @scottbomb, @Neural-network-N):

Could you provide me a `skdump /dev/xxx --save=xxx.bin` binary dumps for testing please? Every drive is different and I would like to see what exact attributes we need quirks for.

Also FYI https://github.com/storaged-project/libblockdev/pull/835

**Comment by Neural-network-N** [comment] 2024-04-29 18:31
> `skdump /dev/xxx --save=xxx.bin`
[Dump_bin.tar.gz](https://github.com/storaged-project/udisks/files/15153311/Dump_bin.tar.gz)

Here you go:

**Comment by tbzatek** [comment] 2024-05-02 13:32
> Here you go:

Thanks, this is useful.

**Comment by bothandeach** [comment] 2024-05-20 19:09
Similar problem maybe .. hardinfo2 says Kingston SA400S37120G has two measurements: one is SMART "self monitoring" = 86C (!), whereas SMART attributes is 24C,  and command line 'smartctl' = 24C.  Self monitoring number is unhelpful.

**Comment by tbzatek** [comment] 2024-05-23 12:33
> Similar problem maybe .. hardinfo2 says Kingston SA400S37120G has two measurements: one is SMART "self monitoring" = 86C (!), whereas SMART attributes is 24C, and command line 'smartctl' = 24C. Self monitoring number is unhelpful.

Can you post the skdump here please?

**Comment by bothandeach** [comment] 2024-05-23 15:31
Raw skdump gives me

Device: sat16:/dev/sdb
Type: 16 Byte SCSI ATA SAT Passthru
Size: 114473 MiB
Model: [KINGSTON SA400S37120G]
Serial: [50026B7782B81C72]
Firmware: [03090004]
SMART Available: yes
Quirks:
Awake: no
SMART Disk Health Good: yes
Off-line Data Collection Status: [Off-line data collection activity was completed without error.]
Total Time To Complete Off-Line Data Collection: 0 s
Self-Test Execution Status: [The previous self-test routine completed without error or no self-test has ever been run.]
Percent Self-Test Remaining: 0%
Conveyance Self-Test Available: yes
Short/Extended Self-Test Available: yes
Start Self-Test Available: yes
Abort Self-Test Available: yes
Short Self-Test Polling Time: 1 min
Extended Self-Test Polling Time: 1 min
Conveyance Self-Test Polling Time: 1 min
Bad Sectors: No such file or directory
Powered On: 4.5 years
Power Cycles: 655
Average Powered On Per Power Cycle: 2.5 days
Temperature: 86.0 C
Attribute Parsing Verification: Good
Overall Status: GOOD
ID# Name                        Value Worst Thres Pretty      Raw            Type    Updates Good Good/Past
  1 raw-read-error-rate         100   100     0   0           0x000000000000 old-age online  n/a  n/a 
  9 power-on-hours              100   100     0   4.5 years   0xbc9a00000000 old-age online  n/a  n/a 
 12 power-cycle-count           100   100     0   655         0x8f0200000000 old-age online  n/a  n/a 
148 attribute-148               100   100     0   n/a         0x000000000000 old-age offline n/a  n/a 
149 attribute-149               100   100     0   n/a         0x000000000000 old-age offline n/a  n/a 
167 attribute-167               100   100     0   n/a         0x000000000000 old-age offline n/a  n/a 
168 attribute-168               100   100     0   n/a         0x000000000000 old-age online  n/a  n/a 
169 attribute-169               100   100     0   n/a         0x920000000000 old-age offline n/a  n/a 
170 available-reserved-space    100   100    10   100%        0x3b0000000000 old-age offline yes  yes 
172 erase-fail-count            100   100     0   0           0x000000000000 old-age online  n/a  n/a 
173 attribute-173               100   100     0   n/a         0x000000000000 old-age offline n/a  n/a 
181 program-fail-count-total    100   100     0   0           0x000000000000 old-age online  n/a  n/a 
182 erase-fail-count-total      100   100     0   0           0x000000000000 old-age offline n/a  n/a 
187 reported-uncorrect          100   100     0   0 sectors   0x000000000000 old-age online  n/a  n/a 
192 power-off-retract-count     100   100     0   396         0x8c0100000000 old-age online  n/a  n/a 
194 temperature-celsius-2        24    27     0   24.0 C      0x180017001b00 old-age online  n/a  n/a 
196 reallocated-event-count     100   100     0   0           0x000000000000 old-age online  n/a  n/a 
199 udma-crc-error-count        100   100     0   0           0x000000000000 old-age online  n/a  n/a 
218 attribute-218               100   100     0   n/a         0x000000000000 old-age online  n/a  n/a 
231 temperature-celsius          86    86     0   86.0 C      0x560000000000 old-age offline n/a  n/a 
233 power-on-seconds-2          100   100     0   n/a         0x574d00000000 old-age online  n/a  n/a 
241 total-lbas-written          100   100     0   321.115 GB  0x622500000000 old-age online  n/a  n/a 
242 total-lbas-read             100   100     0   206.695 GB  0x101800000000 old-age online  n/a  n/a 
244 attribute-244               100   100     0   n/a         0x8f0000000000 old-age offline n/a  n/a 
245 attribute-245               100   100     0   n/a         0x9e0000000000 old-age offline n/a  n/a 
246 attribute-246               100   100     0   n/a         0xceee00000000 old-age offline n/a  n/a

**Comment by tbzatek** [comment] 2024-05-27 10:28
Thanks, but I need binary dump - see above.

**Closed** 2024-06-11 13:06 UTC

**Comment by boredazfcuk** [comment] 2024-06-17 22:35
Better late than never, I guess. Thought I'd upload just in case, as I can only see one other binary dump. 
[Patriot_Burst_240GB.zip](https://github.com/user-attachments/files/15878069/Patriot_Burst_240GB.zip)

**Comment by mozlima** [comment] 2024-06-19 20:33
Hi,
This is binary skdump of KINGSTON SA400S37480G (SBFKQ1.3) :

[KINGSTON SA400S37480G (SBFKQ1.3).zip](https://github.com/user-attachments/files/15905682/KINGSTON.SA400S37480G.SBFKQ1.3.zip)

**Comment by Dirli** [comment] 2024-06-19 22:59
Hi, I'm very sorry, I missed this thread a bit.
GIGABYTE GP-GSTFS31100TNTD
Biwintech SSD SX500 512GB
[gigabyte.tar.gz](https://github.com/user-attachments/files/15906519/gigabyte.tar.gz)
[biwintech.tar.gz](https://github.com/user-attachments/files/15906520/biwintech.tar.gz)

**Comment by tbzatek** [comment] 2024-06-20 16:37
Thanks @boredazfcuk, @mozlima and @Dirli, added as a test case in https://github.com/storaged-project/libblockdev/pull/1033.
