### ISSUE TITLE
malformed url error when attempting to mount device and open with file manager

### ISSUE THREAD

**Issue by keijukainen** [storaged-project/udisks#502] opened 2018-03-08 08:58 UTC
There was a regression from 2.7.5 to 2.7.6. I use the KaOS distro and with udisks 2.7.6 installed I receive an error any time I try to mount a usb device. This occurs when mounting a device through dolphin and also through the device notifier. It's definitely a bug in 2.7.6 because if I downgrade to 2.7.5 everything works fine. See the thread below for full logs and screenshots.

https://forum.kaosx.us/d/2180-malformed-url-when-mounting-device-and-opening-with-dolphin

**Comment by vpodzime** [comment] 2018-03-09 13:48
This is really weird:
```
Mar 04 23:51:22 MYPC kde-open5[1654]: kf5.kio.widgets: Malformed URL: ""
Mar 04 23:51:19 MYPC udisksd[281]: Mounted /dev/sdb1 at /run/media/USER/STORE N GO on behalf of uid 1>
Mar 04 23:51:19 MYPC kernel: FAT-fs (sdb1): Volume was not properly unmounted. Some data may be corrupt>
```

**Comment by vpodzime** [comment] 2018-03-09 13:48
But to me it looks like the device gets mounted just fine.

**Comment by vpodzime** [comment] 2018-03-09 13:50
@keijukainen could you please run ``sudo udisksctl monitor`` before plugging in and trying to open the flash drive? And ideally try with both the working and non-working versions of *udisks* to compare.

**Comment by keijukainen** [comment] 2018-03-09 14:03
attached log. both versions are included.
[error_log.txt](https://github.com/storaged-project/udisks/files/1797101/error_log.txt)

**Comment by mar04** [comment] 2018-03-21 14:05
Same bug here, although I don't know if it's actually udisks or something in KDE, and recent udisk just made it more frequent. Here is KDE bug report from 2016: https://bugs.kde.org/show_bug.cgi?id=370975

**Comment by keijukainen** [comment] 2018-03-22 12:18
After testing a number of different configuration options in 2.7.6 it turns out that the issue is related to libmount. It's not used, as far as I can tell, in 2.7.5 but it's automatically enabled in 2.7.6 if you have it installed on your system. There's no option to turn it off in the configure script. I think the first step should be to create a new option that can be passed to configure like "--disable-libmount". Or disable by default and give users the option to enable it. That might be the better option since it wasn't used in 2.7.5.

What are the consequences of disabling libmount? Udisks appears to work just fine on my system with libmount disabled.

[kaos.zip](https://github.com/storaged-project/udisks/files/1837442/kaos.zip)

I use the attached patch to provide a libmount disable option in the configure script.
```
  patch -Np1 -i "${srcdir}/kaos.patch"
  export DISABLE_LIBMOUNT=1
  ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --libexecdir=/usr/lib \
        --with-systemdsystemunitdir=/usr/lib/systemd/system \
        --disable-static \
        --enable-lvm2 \
        --enable-lvmcache \
        --enable-btrfs \
        --enable-zram \
        --enable-bcache
  make
```

Here is the log from "udisksctl monitor" using 2.7.6 with libmount disabled.
```
Monitoring the udisks daemon. Press Ctrl+C to exit.
06:50:05.122: The udisks-daemon is running (name-owner :1.8).
06:50:13.152: Added /org/freedesktop/UDisks2/drives/Verbatim_STORE_N_GO_1701000000017720
  org.freedesktop.UDisks2.Drive:
    CanPowerOff:                true
    Configuration:              {}
    ConnectionBus:              usb
    Ejectable:                  true
    Id:                         Verbatim-STORE-N-GO-1701000000017720
    Media:                      
    MediaAvailable:             true
    MediaChangeDetected:        true
    MediaCompatibility:         
    MediaRemovable:             true
    Model:                      STORE N GO
    Optical:                    false
    OpticalBlank:               false
    OpticalNumAudioTracks:      0
    OpticalNumDataTracks:       0
    OpticalNumSessions:         0
    OpticalNumTracks:           0
    Removable:                  true
    Revision:                   1100
    RotationRate:               -1
    Seat:                       seat0
    Serial:                     1701000000017720
    SiblingId:                  /sys/devices/pci0000:00/0000:00:1a.0/usb3/3-1/3-1.2/3-1.2:1.0
    Size:                       15623782400
    SortKey:                    01hotplug/1521719413148074
    TimeDetected:               1521719413148074
    TimeMediaDetected:          1521719413148074
    Vendor:                     Verbatim
    WWN:                        
06:50:13.162: Added /org/freedesktop/UDisks2/block_devices/sdb
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/sdb
    DeviceNumber:               2064
    Drive:                      '/org/freedesktop/UDisks2/drives/Verbatim_STORE_N_GO_1701000000017720'
    HintAuto:                   true
    HintIconName:               
    HintIgnore:                 false
    HintName:                   
    HintPartitionable:          true
    HintSymbolicIconName:       
    HintSystem:                 false
    Id:                         
    IdLabel:                    
    IdType:                     
    IdUUID:                     
    IdUsage:                    
    IdVersion:                  
    MDRaid:                     '/'
    MDRaidMember:               '/'
    PreferredDevice:            /dev/sdb
    ReadOnly:                   false
    Size:                       15623782400
    Symlinks:                   /dev/disk/by-id/usb-Verbatim_STORE_N_GO_1701000000017720-0:0
                                /dev/disk/by-path/pci-0000:00:1a.0-usb-0:1.2:1.0-scsi-0:0:0:0
    UserspaceMountOptions:      
  org.freedesktop.UDisks2.PartitionTable:
    Partitions:         []
    Type:               dos
06:50:13.255: Added /org/freedesktop/UDisks2/block_devices/sdb1
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/sdb1
    DeviceNumber:               2065
    Drive:                      '/org/freedesktop/UDisks2/drives/Verbatim_STORE_N_GO_1701000000017720'
    HintAuto:                   true
    HintIconName:               
    HintIgnore:                 false
    HintName:                   
    HintPartitionable:          true
    HintSymbolicIconName:       
    HintSystem:                 false
    Id:                         by-uuid-B889-6B93
    IdLabel:                    STORENGO
    IdType:                     vfat
    IdUUID:                     B889-6B93
    IdUsage:                    filesystem
    IdVersion:                  FAT32
    MDRaid:                     '/'
    MDRaidMember:               '/'
    PreferredDevice:            /dev/sdb1
    ReadOnly:                   false
    Size:                       15618055680
    Symlinks:                   /dev/disk/by-id/usb-Verbatim_STORE_N_GO_1701000000017720-0:0-part1
                                /dev/disk/by-label/STORENGO
                                /dev/disk/by-partuuid/b917a57e-01
                                /dev/disk/by-path/pci-0000:00:1a.0-usb-0:1.2:1.0-scsi-0:0:0:0-part1
                                /dev/disk/by-uuid/B889-6B93
    UserspaceMountOptions:      
  org.freedesktop.UDisks2.Filesystem:
    MountPoints:        
    Size:               0
  org.freedesktop.UDisks2.Partition:
    Flags:              0
    IsContained:        false
    IsContainer:        false
    Name:               
    Number:             1
    Offset:             5726208
    Size:               15618055680
    Table:              '/org/freedesktop/UDisks2/block_devices/sdb'
    Type:               0x0c
    UUID:               b917a57e-01
06:50:15.731: Added /org/freedesktop/UDisks2/jobs/3
  org.freedesktop.UDisks2.Job:
    Bytes:              0
    Cancelable:         true
    ExpectedEndTime:    0
    Objects:            ['/org/freedesktop/UDisks2/block_devices/sdb1']
    Operation:          filesystem-mount
    Progress:           0.0
    ProgressValid:      false
    Rate:               0
    StartTime:          1521719415729379
    StartedByUID:       0
06:50:15.756: /org/freedesktop/UDisks2/jobs/3: org.freedesktop.UDisks2.Job::Completed (true, '')
06:50:15.756: Removed /org/freedesktop/UDisks2/jobs/3
06:50:15.756: /org/freedesktop/UDisks2/block_devices/sdb1: org.freedesktop.UDisks2.Filesystem: Properties Changed
  MountPoints:          /run/media/USER/STORENGO
```

**Comment by vojtechtrefny** [comment] 2018-03-22 12:56
Thank you for investigating this. We use libmount for parsing/getting userspace mount options in UDisks 2.7.6 (see property `UserspaceMountOptions`) this was added in #460 

Allowing to disable this feature might be a good temporary workaround, but it'd be better to actually fix the bug causing this issue. I'll try to test this a little bit more next week and hopefully find the issue behind this.

**Comment by hbayindir** [comment] 2018-04-15 10:54
I'm having the same problem, and feels like a race condition for me, because:
- If I tell KDE to mount and open dolphin immediately, I get the malformed URL.
- If I tell KDE to mount only, and open the folder ~2 seconds later, everything works as it should.

Running latest KDE on Debian/Testing.

**Comment by vojtechtrefny** [comment] 2018-04-25 07:13
This is definitely some sort of race condition, but as far as I can tell udisks works as expected. I was able to reproduce this issue in approximately 50 % cases, but udisks always mounted the device. The change  @keijukainen mentioned is actually in a different part of the code and it only adds a new property that is set after the mount successfully finished. Maybe the extra change event (caused by updating the `UserspaceMountOptions` property) triggers some handler in KDE and that causes this issue, but it's really hard for me to debug this -- I don't know the KDE code and the error message "Malformed URL" is not helpful. And the KDE bug is from 2016 so this actually happened before this change.
I'll try to test this some more, but I think this needs some attention from KDE developers.

**Comment by keijukainen** [comment] 2018-04-25 11:26
I ran a few tests to find out which user options were being returned.  In the udisksutabmonitor.c file, I added some code to fs_has_user_options() and logged the values returned from mnt_fs_get_user_options().  When I checked the log I discovered a long list (can't remember exact number but likely 20+ entries) every time I plugged in a usb drive.  Every log entry contained "(null)" except for one which was always uhelper=udisks2.  There were never any other user options.  Not sure if this has any relevance to the bug but I thought I would mention it.

**Comment by hbayindir** [comment] 2018-04-25 12:49
@vojtechtrefny I've observed the behavior of the KDE and the mounting process a bit more. While it's a superficial observation, mouting completes *after* I get the `malformed URL` error.

It looks like the KDE KIO gets an empty path (`kf5.kio.widgets: Malformed URL: ""`) when it tries to get a path for the mounted drive. Can it be that udisks is returning an empty string for the path as an answer to the querying service, since the mouting process is not complete yet?

I have some ideas, but they are too vague at that point.

**Comment by vpodzime** [comment] 2018-05-01 21:04
Thanks for the extra investigation @davidedmundson! I take it we can now close this issue?

**Comment by davidedmundson** [comment] 2018-05-01 21:34
I think so

**Closed** 2018-05-01 23:04 UTC

**Comment by eanbowman** [comment] 2019-07-04 13:03
Same error. Connecting a FAT32 MicroSD. When the notification comes up and I click that, the Malformed URL error occurs. When I go through Dolphin in a separate window and click the device in the list on the left, that method works. Somehow the notification isn't getting the device URL properly.

**Comment by eanbowman** [comment] 2019-07-04 13:03
Same error when connecting MTP devices too, of course. Devices tried: LG Q Stylo + and GoPro Hero 5 Session.

**Comment by vpodzime** [comment] 2019-07-05 08:51
So isn't it just KDE mangling the URL in the notification? GNOME does that too. Try something like `notify-send Test "Some long URL: https://github.com/storaged-project/udisks/issues/502#issuecomment-508475370"` -- when I click the link in the notification, the URL is incomplete.

**Comment by eanbowman** [comment] 2019-07-05 13:24
@vpodzime I guarantee that's what it is. I'm sorry I posted my reply in the repository for this rather than the right place. Just :+1:  for this issue, I guess.
