### ISSUE TITLE
SetFlags() method may reset the partition type

### ISSUE THREAD

**Issue by intrigeri** [storaged-project/udisks#418] opened 2017-10-09 09:04 UTC
Hi!

The SetFlags() method sometimes resets the type of the partition it's called on. I don't know if it's on purpose and I could not find anything about it in DevHelp. The integration test I'm adding is based on #416, that adds a test case I'm extending here.

**Comment by vojtechtrefny** [comment] 2017-11-27 09:36
Thank you for the report (and the test too). The problem is actually in libblockdev, this -- https://github.com/storaged-project/libblockdev/pull/306 -- should fix it.

**Comment by intrigeri** [comment] 2017-11-27 10:02
Great! Thanks for investigating, identifying the root cause and proposing a fix :)

**Comment by vojtechtrefny** [comment] 2017-11-29 16:34
libblockdev change is merged and the test is passing -- #464 -- so I guess we can close this.

**Closed by vojtechtrefny** 2017-11-29 16:34 UTC
