### ISSUE TITLE
Clean up GLib-GObject-WARNINGs

### ISSUE THREAD

**Issue by tasleson** [storaged-project/udisks#122] opened 2016-10-28 19:51 UTC
I'm seeing a ton of these warning when running:

```
(lt-udisksd:25714): GLib-GObject-WARNING **: g_object_notify: object class 'UDisksLinuxBlockObject' has no property named 'block-lvm2'
(lt-udisksd:25714): GLib-GObject-WARNING **: g_object_notify: object class 'UDisksLinuxBlockObject' has no property named 'physical-volume'
(lt-udisksd:25714): GLib-GObject-WARNING **: g_object_notify: object class 'UDisksLinuxLogicalVolumeObject' has no property named 'logical-volume'
(lt-udisksd:25714): GLib-GObject-WARNING **: g_object_notify: object class 'UDisksLinuxVolumeGroupObject' has no property named 'volume-group'
(lt-udisksd:25714): GLib-GObject-WARNING **: g_object_notify: object class 'UDisksObjectSkeleton' has no property named 'manager-bcache'
(lt-udisksd:25714): GLib-GObject-WARNING **: g_object_notify: object class 'UDisksObjectSkeleton' has no property named 'manager-btrfs'
(lt-udisksd:25714): GLib-GObject-WARNING **: g_object_notify: object class 'UDisksObjectSkeleton' has no property named 'manager-iscsi-initiator'
(lt-udisksd:25714): GLib-GObject-WARNING **: g_object_notify: object class 'UDisksObjectSkeleton' has no property named 'manager-lsm'
(lt-udisksd:25714): GLib-GObject-WARNING **: g_object_notify: object class 'UDisksObjectSkeleton' has no property named 'manager-lvm2'
(lt-udisksd:25714): GLib-GObject-WARNING **: g_object_notify: object class 'UDisksObjectSkeleton' has no property named 'manager-zram'
...
```

It would be good to fix these so we can run with `G_DEBUG=fatal-warnings`

**Comment by tbzatek** [comment] 2019-06-05 16:26
This is related to modules and the way how we attach extra interfaces to published d-bus objects. Purely cosmetical issue as verified during my last memleak evaluation.

This can be solved either by creating extra properties on the parent object (nasty) or by tweaking the generated `GDBus` code for module interfaces (less nasty, still nasty though).

**Comment by tbzatek** [comment] 2019-06-07 13:34
This is caused by the default handlers of `GDBusObject` _interface-added_ and _interface-removed_ signals as generated by `gdbus-codegen`, triggered by `g_dbus_object_skeleton_add_interface()`. The most clean way would be to modify the handlers and check for presence of the particular property.

The change would look this way:
```
--- udisks-generated.c	2019-06-07 15:31:54.253151447 +0200
+++ udisks-generated.c.bak	2019-06-07 15:32:36.118458048 +0200
@@ -36951,8 +36951,10 @@
   /* info can be NULL if the other end is using a D-Bus interface we don't know
    * anything about, for example old generated code in this process talking to
    * newer generated code in the other process. */
-  if (info != NULL)
-    g_object_notify (G_OBJECT (object), info->hyphen_name);
+  if (info != NULL) {
+    if (g_object_interface_find_property (UDISKS_OBJECT_GET_IFACE (object), info->hyphen_name))
+      g_object_notify (G_OBJECT (object), info->hyphen_name);
+  }
 }
 
 /**
```

However this would mean modifying generated code and while `gdbus-codegen` doesn't change that often, there's still a risk this will break in the future.

**Comment by tbzatek** [comment] 2019-06-10 15:13
My other attempt to fix this without modifying the generated code turned out to be a dead end. I've tried to intercept and stop emission of the `GDBusObject::interface-added` and `::interface-removed` signals in case of module interfaces, by calling `g_signal_stop_emission_by_name()`, preventing other handlers to run. However it seems there are several handlers connected and some of them need to be run to ensure correct `GDBus` functionality.

I've also tried retrieve `GDBusObject` interface from newly constructed objects and overload the `interface-added` and `interface-removed` methods. That's not a clean solution either and modifying class handlers propagate globally, leading to potentially unwanted results.

**Comment by tbzatek** [comment] 2019-06-10 15:43
One other wild idea would be to somehow merge (incl. all annotations and comments) all the interface definition XML files into one during build. However since we ship `udisks-generated.h` as a part of public API, we'd need to generate two set of files.

**Comment by vpodzime** [comment] 2019-06-16 19:14
> However since we ship `udisks-generated.h` as a part of public API, we'd need to generate two set of files.

Why would we need two sets of files?

**Comment by tbzatek** [comment] 2019-06-27 15:31
Note to myself: merged interfaces will make `modules/iscsi/udisksiscsidbusutil.c` obsolete. One Coverity warning less.

**Closed** 2020-04-08 09:37 UTC
