### ISSUE TITLE
S.M.A.R.T. on USB disk

### ISSUE THREAD

**Issue by bhack** [storaged-project/udisks#423] opened 2017-10-11 11:08 UTC
USB disk seems to works file with command line `smartctl`.
Why the usb disks are not supported in the SMART api here?
See also https://bugzilla.gnome.org/show_bug.cgi?id=757784
And https://bugs.launchpad.net/ubuntu/+source/gnome-disk-utility/+bug/1540110

**Comment by bhack** [comment] 2017-10-11 20:10
I think that `ret == 0` is wrong. See https://github.com/storaged-project/udisks/blob/master/src/tests/dbus-tests/test_drive_ata.py#L16.
See the official [exit status](https://www.smartmontools.org/browser/trunk/smartmontools/smartctl.8.in)

**Comment by bhack** [comment] 2017-10-11 20:48
Also on some type of disks you need to pass `-d` option

Edit: Probably default device type auto is enough for the latest releases

**Comment by bhack** [comment] 2017-10-11 21:53
So test seems not correct here cause the wrong interpretation of the return value of smartctl. But when you will correct the test and you have some kind of usb disks to test on the test will fail. The use here of the large unmaintained upstream libatasmart that for sure is still quite limited on the [old pid/vid list](http://git.0pointer.net/libatasmart.git/tree/atasmart.c#n2670) and will be disaligned by new version of smarctl output.

**Comment by vpodzime** [comment] 2017-10-27 12:05
> I think that ret == 0 is wrong. See https://github.com/storaged-project/udisks/blob/master/src/tests/dbus-tests/test_drive_ata.py#L16.
> See the official exit status

Yes, this should be fixed.

**Comment by vpodzime** [comment] 2017-10-27 12:05
> Also on some type of disks you need to pass -d option
> 
> Edit: Probably default device type auto is enough for the latest releases

I believe the path/name of the device should be enough for modern *smartctl* to choose the right command set.

**Comment by vpodzime** [comment] 2017-10-27 12:11
> The use here of the large unmaintained upstream libatasmart that for sure is still quite limited on the old pid/vid list and will be disaligned by new version of smarctl output.

Would you mind creating a separate issue for this? *smartctl* should probably be used as the source of the information. But then again, there's a penalty of fork&exec of the utility periodically instead of using a library. Plus the price of parsing the complicated output. If only *smartclt* could provide a JSON output or something. Or, ideally, if something could populate and maintain a subtree like ``/sys/block/DEVICE/smart`` with all the data.

**Comment by vpodzime** [comment] 2017-10-27 12:22
> USB disk seems to works file with command line smartctl.
> Why the usb disks are not supported in the SMART api here?

I just tested two different USB disks -- one real USB 3.0 disk and one ordinary 2.5" SATA HDD in a USB 3.0 case -- and both worked just fine with *udisks2*. All the SMART data was correctly provided by the daemon and visible in *GNOME Disks*. So this is definitely a generic issue with USB disks.

I think the only real problem here is described in your comment https://github.com/storaged-project/udisks/issues/423#issuecomment-335960169 regarding *libatasmart* and *smartctl*. But as I explained before, that requires a separate issue and some discussion/research.

**Comment by vpodzime** [comment] 2017-10-27 12:33
> See the official exit status

The problem is that their man page obviously lies, because:
```
# smartctl -a /dev/sdb
smartctl 6.5 2016-05-07 r4318 [x86_64-linux-4.14.0-0.rc6.git0.1.fc28.x86_64] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sdb: Unknown USB bridge [0x46f4:0x0001 (0x000)]
Please specify device type with the -d option.

Use smartctl -h to get a usage summary

[root@localhost koki]# echo $?
1
```

Doesn't look to me like a failure to parse the command line...

**Comment by bhack** [comment] 2017-10-27 12:39
I think that you are not considering the case when the disk has some hind of error when you don't have 1 result but other kind of retun code as man.

**Comment by bhack** [comment] 2017-10-27 12:40
Ok I've seen the commit that cover failure disks cases

**Closed** 2017-10-30 07:24 UTC
