### ISSUE TITLE
GNOME Disk does not see the USB drive

### ISSUE THREAD

**Issue by wolfv6** [storaged-project/udisks#207] opened 2017-02-20 08:01 UTC
Here is what I did:

From GNOME Disks > Format Disk
    Partitioning: Compatible with all systems (DOS).
    Click format (the volumes grid became entirely blue indicating that the drive was made free).
    Close the partitioning window.
From Nautilus, click on unmount button.
Then pull the USB drive out and plug it back in.
Now the USB drive does not show up in Nautilus nor GNOME Disks.

I am running Fedora 25, Gnome 3.22.2, Haswell Intel NUC Kit D54250WYK, Intel Core i5-4250U.
The USB drive is 1.0 GB Drive VBTM Store 'n' Go.

**Comment by wolfv6** [comment] 2017-02-20 08:23
Update:
I insterted the USB drive in Chrome OS, and it recognized and reformatted the USB drive: 1.0 GB Drive VBTM Store 'n' Go.

Then I put the USB drive in Fedora 25 PC again and it worked with GNOME Disk without incident.

**Comment by vpodzime** [comment] 2017-06-23 09:25
@wolfv6, could you please try to reproduce the issue once more? Ideally with Fedora 26? Thanks!

**Comment by wolfv6** [comment] 2017-06-23 09:59
@vpodzime,  Sorry, I don't have that USB drive any more.

**Comment by vpodzime** [comment] 2017-06-26 07:00
> @vpodzime, Sorry, I don't have that USB drive any more.

OK. Since this seems to be working just fine with other USB drives, I'm going to close this issue. Feel free to reopen it if you spot the problem again.

**Closed by vpodzime** 2017-06-26 07:00 UTC
