### ISSUE TITLE
udisks2 crashes when libblockdev plugins are missing

### ISSUE THREAD

**Issue by paulmenzel** [storaged-project/udisks#1143] opened 2023-07-11 09:55 UTC
Patrice Duroux submitted [bug report #1040793][1] to the Debian BTS, containing the trace for *udisks2* 2.10.0-2 below.

```
       Message: Process 4640 (udisksd) of user 0 dumped core.

                Module libudev.so.1 from deb systemd-253.5-1.amd64
                Module libsystemd.so.0 from deb systemd-253.5-1.amd64
                Stack trace of thread 4640:
                #0  0x00007faa5ad3c1e7 g_log_writer_default (libglib-2.0.so.0 +
0x641e7)
                #1  0x00007faa5ad39b61 g_log_structured_array (libglib-2.0.so.0
+ 0x61b61)
                #2  0x00007faa5ad39ecb g_log_structured (libglib-2.0.so.0 +
0x61ecb)
                #3  0x0000556c3f1aed34 udisks_log (udisksd + 0x53d34)
                #4  0x0000556c3f17a303 n/a (udisksd + 0x1f303)
                #5  0x00007faa5ae37fe6 n/a (libgobject-2.0.so.0 + 0x1bfe6)
                #6  0x00007faa5ae39bc3 g_object_new_valist (libgobject-2.0.so.0
+ 0x1dbc3)
                #7  0x00007faa5ae3a219 g_object_new (libgobject-2.0.so.0 +
0x1e219)
                #8  0x0000556c3f17aaac udisks_daemon_new (udisksd + 0x1faac)
                #9  0x0000556c3f1796f2 n/a (udisksd + 0x1e6f2)
                #10 0x00007faa5af92421 n/a (libgio-2.0.so.0 + 0x116421)
                #11 0x00007faa5af2d5e3 n/a (libgio-2.0.so.0 + 0xb15e3)
                #12 0x00007faa5af2e1d3 n/a (libgio-2.0.so.0 + 0xb21d3)
                #13 0x00007faa5af82e32 n/a (libgio-2.0.so.0 + 0x106e32)
                #14 0x00007faa5af2d5e3 n/a (libgio-2.0.so.0 + 0xb15e3)
                #15 0x00007faa5af2d619 n/a (libgio-2.0.so.0 + 0xb1619)
                #16 0x00007faa5ad31e2f g_main_context_dispatch
(libglib-2.0.so.0 + 0x59e2f)
                #17 0x00007faa5ad32208 n/a (libglib-2.0.so.0 + 0x5a208)
                #18 0x00007faa5ad324bf g_main_loop_run (libglib-2.0.so.0 +
0x5a4bf)
                #19 0x0000556c3f17942e main (udisksd + 0x1e42e)
                #20 0x00007faa5ab1d6ca __libc_start_call_main (libc.so.6 +
0x276ca)
                #21 0x00007faa5ab1d785 __libc_start_main_impl (libc.so.6 +
0x27785)
                #22 0x0000556c3f179551 _start (udisksd + 0x1e551)

                Stack trace of thread 4643:
                #0  0x00007faa5abf6eb9 syscall (libc.so.6 + 0x100eb9)
                #1  0x00007faa5ad8bb4c g_cond_wait_until (libglib-2.0.so.0 +
0xb3b4c)
                #2  0x00007faa5acfbfc1 n/a (libglib-2.0.so.0 + 0x23fc1)
                #3  0x00007faa5ad5efe2 n/a (libglib-2.0.so.0 + 0x86fe2)
                #4  0x00007faa5ad5e63d n/a (libglib-2.0.so.0 + 0x8663d)
                #5  0x00007faa5ab7e3ec start_thread (libc.so.6 + 0x883ec)
                #6  0x00007faa5abfea1c __clone3 (libc.so.6 + 0x108a1c)

                Stack trace of thread 4642:
                #0  0x00007faa5abf6eb9 syscall (libc.so.6 + 0x100eb9)
                #1  0x00007faa5ad8b9a0 g_cond_wait (libglib-2.0.so.0 + 0xb39a0)
                #2  0x00007faa5acfbfeb n/a (libglib-2.0.so.0 + 0x23feb)
                #3  0x00007faa5ad5ec82 n/a (libglib-2.0.so.0 + 0x86c82)
                #4  0x00007faa5ad5e63d n/a (libglib-2.0.so.0 + 0x8663d)
                #5  0x00007faa5ab7e3ec start_thread (libc.so.6 + 0x883ec)
                #6  0x00007faa5abfea1c __clone3 (libc.so.6 + 0x108a1c)

                Stack trace of thread 4644:
                #0  0x00007faa5abf19ef __GI___poll (libc.so.6 + 0xfb9ef)
                #1  0x00007faa5ad3217e n/a (libglib-2.0.so.0 + 0x5a17e)
                #2  0x00007faa5ad324bf g_main_loop_run (libglib-2.0.so.0 +
0x5a4bf)
                #3  0x00007faa5af98156 n/a (libgio-2.0.so.0 + 0x11c156)
                #4  0x00007faa5ad5e63d n/a (libglib-2.0.so.0 + 0x8663d)
                #5  0x00007faa5ab7e3ec start_thread (libc.so.6 + 0x883ec)
                #6  0x00007faa5abfea1c __clone3 (libc.so.6 + 0x108a1c)

                Stack trace of thread 4641:
                #0  0x00007faa5abf19ef __GI___poll (libc.so.6 + 0xfb9ef)
                #1  0x00007faa5ad3217e n/a (libglib-2.0.so.0 + 0x5a17e)
                #2  0x00007faa5ad3229c g_main_context_iteration
(libglib-2.0.so.0 + 0x5a29c)
                #3  0x00007faa5ad322e1 n/a (libglib-2.0.so.0 + 0x5a2e1)
                #4  0x00007faa5ad5e63d n/a (libglib-2.0.so.0 + 0x8663d)
                #5  0x00007faa5ab7e3ec start_thread (libc.so.6 + 0x883ec)
                #6  0x00007faa5abfea1c __clone3 (libc.so.6 + 0x108a1c)
                ELF object binary architecture: AMD x86-64
```

As a result, `mdadm` is now an indirect dependency through *libblockdev-mdraid3*. It’d be great, if users would not need to install *mdadm*.

[1]: https://bugs.debian.org/1040793

**Comment by paulmenzel** [comment] 2023-07-11 09:56
\cc @mbiebl

**Comment by vojtechtrefny** [comment] 2023-07-11 10:05
Duplicate of https://github.com/storaged-project/udisks/issues/1142

**Closed by vojtechtrefny** 2023-07-11 10:05 UTC
