### ISSUE TITLE
unlock with --key-file

### ISSUE THREAD

**Issue by hinxx** [storaged-project/udisks#316] opened 2017-06-19 14:32 UTC
I'm trying to use the `--key-file` with unlock and fails with the following:

`~/luks/udisks $ /usr/local/bin/udisksctl unlock -b /dev/sdd1 --key-file ~/.backup.key
Error unlocking /dev/sdd1: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error unlocking /dev/sdd1: Command-line 'cryptsetup luksOpen "/dev/sdd1" "luks-061b69b9-1926-438f-8b4a-03726e2c29b4"' exited with non-zero exit status 1: `

Executing cryptsetup manually also fails:

`~/luks/udisks $ cryptsetup luksOpen "/dev/sdd1" "luks-061b69b9-1926-438f-8b4a-03726e2c29b4"
Device /dev/sdd1 doesn't exist or access denied.`

Works with sudo, but I do not want to use sudo:

`~/luks/udisks $ sudo cryptsetup luksOpen "/dev/sdd1" "luks-061b69b9-1926-438f-8b4a-03726e2c29b4"
Enter passphrase for /dev/sdd1:`

Any plans on having it work without sudo?

**Comment by vpodzime** [comment] 2017-06-20 07:38
> Any plans on having it work without sudo?

Unlocking LUKS device requires root privileges. However, ``udiskctl`` should prompt for sudo passphrase when doing the unlock. Is that not happening? I take it you have *sudo* configured properly?

**Comment by vpodzime** [comment] 2017-06-20 09:53
Are you sure the user can also read the key file? And is the key file correct? What if you try using it with ``sudo cryptsetup luksOpen``?

**Comment by hinxx** [comment] 2017-06-20 10:24
Silly question: is key file supposed to hold the passphrase? .. or something else?

I've put passphrase into hkbackup.key file and using it against cryptsetup results in:

`$ sudo cryptsetup --key-file=/home/hinkokocevar/.hkbackup.key luksOpen /dev/sdd1 1tb`

`No key available with this passphrase.`

**Comment by vpodzime** [comment] 2017-06-20 10:40
> Silly question: is key file supposed to hold the passphrase?

Yes, it has to be **precisely** the passphrase. Maybe you have an extra newline at the end or something?

**Comment by hinxx** [comment] 2017-06-20 11:27
You were right, 0x0a somehow sneaked in the key file.
Now I can do:

`$ sudo cryptsetup --key-file=/home/hinkokocevar/.hkbackup.key luksOpen /dev/sdd1 1tb`


So the key file is proper.
Going back to using `udisksctl`, still fails:
`$ /usr/local/bin/udisksctl unlock --key-file=/home/hinkokocevar/.hkbackup.key -b /dev/sdd1
Error unlocking /dev/sdd1: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error unlocking /dev/sdd1: Command-line 'cryptsetup luksOpen "/dev/sdd1" "luks-061b69b9-1926-438f-8b4a-03726e2c29b4" ' exited with non-zero exit status 1:`

And running it manually suggests that the permissions is the issue:

`$ cryptsetup luksOpen "/dev/sdd1" "luks-061b69b9-1926-438f-8b4a-03726e2c29b4"
Device /dev/sdd1 doesn't exist or access denied.`

This works though:

`$ sudo cryptsetup luksOpen "/dev/sdd1" "luks-061b69b9-1926-438f-8b4a-03726e2c29b4"`



I really like the fact that `udisksctl` does not need superuser permissions to mount the drive as opposed to `cryptsetup` ..

**Comment by vpodzime** [comment] 2017-06-21 07:23
@hinxx, any chances you could try it with *udisks-2.7.0*? It's no longer using the ``cryptsetup`` utility and it works for me just fine. Which version of *udisks* are you using? (so that I can try to reproduce and debug the issue)

**Comment by hinxx** [comment] 2017-06-21 07:50
@vpodzime I was using GIT sources, compiled locally on Linux Mint.
I get the same result if I take udisks-2.7.0 from releases and compile it (installed into /usr/local/).

Now I've removed the stock udisks2 packages from the system (hope I did not break everything :/) and the error now is:

`~/luks/udisks-2.7.0 $ /usr/local/bin/udisksctl unlock --key-file=/home/hinkokocevar/.hkbackup.key -b /dev/sdd1
Error connecting to the udisks daemon: Error calling StartServiceByName for org.freedesktop.UDisks2: Timeout was reached`

**Comment by vpodzime** [comment] 2017-06-21 08:05
Looks like *udisks* fails to start automatically, which is understandable given its location and possibly missing dependencies (namely *libblockdev*). Please try it again with the "stock" *udisks2* and tell me what version of *udisks2* that is. Thanks!

**Comment by hinxx** [comment] 2017-06-21 09:17
This is what was installed on my system before removing:
```
$ dpkg -l|grep udisks
ii  gir1.2-udisks-2.0:amd64                      2.1.7-1ubuntu1                               amd64        GObject based library to access udisks2 - introspection data
ii  libudisks2-0:amd64                           2.1.7-1ubuntu1                               amd64        GObject based library to access udisks2
rc  udisks2                                      2.1.7-1ubuntu1                               amd64        D-Bus service to access and manipulate storage devices
```


Should I have `udisksd` installed somewhere? I see it in `udisks-2.7.0/src/.libs/udisksd`, but not in the system folders after `make install`..

**Comment by hinxx** [comment] 2017-06-21 09:48
I managed to find some install path differences between Ubuntu udisks2 and udisks-2.7.0 and tried to compensate. Also I installed udisks-2.7.0 and libblockdev (git) into /usr. Now I see `/usr/libexec/udisks2/udisksd` in system folder.

Trying to start it I get the error:

```
 # /usr/libexec/udisks2/udisksd -rd
udisks-Message: [14072]: udisks daemon version 2.7.0 starting [main.c:145, main()]

** (udisksd:14072): WARNING **: Failed to load config files: Failed to get contents of the config dir (/etc/libblockdev/conf.d/)Error opening directory '/etc/libblockdev/conf.d/': No such file or directory. Using the built-in config

** (udisksd:14072): WARNING **: Cannot load the MDRAID plugin: The 'mdadm' utility is not available

(udisksd:14072): udisks-ERROR **: [14072]: Error initializing libblockdev library: Failed to load plugins (g-bd-init-error-quark, 0) [udisksdaemon.c:269, udisks_daemon_constructed()]
Trace/breakpoint trap (core dumped)
```

**Comment by hinxx** [comment] 2017-06-21 10:07
OK, finally.. it works :)

I had to install newer version of mdadm (3.4) than the one available in the stock DEB repo (3.3).
Then the udisksd started:
```
# /usr/libexec/udisks2/udisksd -rd
udisks-Message: [4918]: udisks daemon version 2.7.0 starting [main.c:145, main()]
udisks-Message: [4918]: Acquired the name org.freedesktop.UDisks2 on the system message bus [main.c:88, on_name_acquired()]

```
Then I could do:

```
$ udisksctl unlock --key-file=/home/hinkokocevar/.hkbackup.key -b /dev/sdd1
Unlocked /dev/sdd1 as /dev/dm-0.
$ udisksctl mount -b /dev/dm-0
Mounted /dev/dm-0 at /run/media/hinkokocevar/ESSbackup.

```

@vpodzime , thanks for helping!!

**Comment by hinxx** [comment] 2017-06-22 07:10
I have put together a backup script that I want to run each day using cron.
If I execute the script manually all happens as expected.
When cron job is started I get the following error when trying to unlock the drive:
```
Error creating textual authentication agent: Error opening current controlling terminal for the process (`/dev/tty'): No such device or address (polkit-error-quark, 0)
Error unlocking /dev/sdd1: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorizedCanObtain: Not authorized to perform operation
```

Any ideas on how to fix this one?

**Comment by vpodzime** [comment] 2017-06-22 07:56
> OK, finally.. it works :)

Great! :)

**Comment by vpodzime** [comment] 2017-06-22 08:01
> Any ideas on how to fix this one?

Not really. The problem is that *udisks* actually needs the root privileges to unlock the device. It uses *PolicyKit* to check if the user doing the operation has administrator privileges. *PolicyKit* is what asks for the *sudo* password in such cases. And with a cron job it has no way to do that. Hence the above error. You need to either make sure the script is run as ``root`` or use ``sudo`` somewhere in it and make sure the user the cron job is being run as has password-less *sudo* enabled (at least for the particular command).

**Comment by vpodzime** [comment] 2017-06-22 08:02
I'm closing this issue as the original problem was resolved. Please note that the discussion can continue anyway.

**Closed by vpodzime** 2017-06-22 08:02 UTC

**Comment by hinxx** [comment] 2017-06-22 09:39
OK.

Funny thing is that I do not have to provide any password when trying to unlock the drive, and I'm not using `sudo` at all. If _PolicyKit_ checks for super user access I should be prompted for password even when running the script from the terminal, if I understand correctly. Also I need to supply password for `sudo`, in other words I do not have password-less `sudo` enabled..

**Comment by vpodzime** [comment] 2017-06-23 07:13
Hmm, that looks like quite a serious bug somewhere. Bug obviously the mechanism is working because it fails in the cron job. This is really weird.

**Comment by vpodzime** [comment] 2017-06-23 07:14
Have you tried using systemd timer instead of a cron job? I think you should be able to specify the user to run the timed service as.

**Comment by hinxx** [comment] 2017-06-23 08:35
I use user crontab to start the backup. It runs as the same user as when I run it manually. I'll see if systemd makes any difference.

I've forked the repo and made a simple hack to get it working with cron. I know that it is totaly not what should be allowed, but I'm quite supprised that it does the job. There's something fishy going on with polkit..

**Comment by alexandrufulop** [comment] 2018-08-08 11:30
[Possible solution]

One possible way to do it is:

`cat your-key-file | cryptsetup -v luksOpen /dev/encrypted your-encrypted-name`
