### ISSUE TITLE
udisks API does not allow device vs partition queries

### ISSUE THREAD

**Issue by aruiz** [storaged-project/udisks#237] opened 2017-04-12 04:36 UTC
the org.freedesktop.UDisk interface has an EnumerateDevices method that basically enumartes any volume (which is kind of misleading in itself)

There is no way to list actual devices, and from there, list partitions for any particular device, you need to infer that from the device names which is kinda tricky.

The use-case for this is the fedora-arm-installer that I'm trying to port to python, I want to be able to find a partition with label "_/" within a specific device.

**Comment by vojtechtrefny** [comment] 2017-04-12 06:50
Hi, if you are using Python, it might be better to use [Blivet](https://github.com/rhinstaller/blivet). It has a "tree-like" structure of devices so it is really simple to get list of partitions for a disk.
But if you really want to use udisks, we can add something like a `Partitions` property to `.Block` interface that will return list of object paths of partitions on this device (similar to the existing `MDRaid` property).

**Comment by vpodzime** [comment] 2017-06-23 09:32
> the org.freedesktop.UDisk interface has an EnumerateDevices method that basically enumartes any volume (which is kind of misleading in itself)

Looks like the old *UDisks* to me. This is *UDisks2* and I don't see any such method. Is adding ``EnumerateBlockDevices()`` and ``EnumerateDevicePartitions()`` what you need/want to be added?

**Comment by aruiz** [comment] 2017-06-23 12:06
Yes, if we could add this to UDisk2 that'd be great.

**Comment by vojtechtrefny** [comment] 2017-07-20 12:35
#352 adds `Partitions` property to `PartitionsTable` interface to list all partitions on a device. This should (at least a little) help with this issue.

**Comment by vpodzime** [comment] 2017-07-28 05:21
#352 is now merged. I'm closing this issue as I believe the problem is now resolved. Please feel free to reopen it if there's still something missing.

**Closed by vpodzime** 2017-07-28 05:21 UTC
