### ISSUE TITLE
Allow mkfs options to be specified in Block.Format

### ISSUE THREAD

**Issue by JeffMoyer** [storaged-project/udisks#722] opened 2020-01-10 22:28 UTC
I'd like to be able to specify mkfs options via the dbus interface.  Cockpit makes use of udisks for creating and mounting file systems.  I'd like to pass through "-m reflink=0" to mkfs.xfs so that mount -o dax will work (the two options are incompatible, and reflink is enabled by default).

**Comment by vojtechtrefny** [comment] 2020-03-12 07:27
Duplicate of #583

**Closed by vojtechtrefny** 2020-03-12 07:27 UTC
